import { createContext, useContext, useEffect, useMemo, useState } from "react";

const STORAGE_KEY = "tea-traceability-language";

const dictionaries = {
  id: {
    "common.active": "Aktif",
    "common.inactive": "Belum aktif",
    "common.configured": "Sudah diisi",
    "common.notConfigured": "Belum diisi",
    "common.back": "Kembali",
    "common.cancel": "Batal",
    "common.save": "Simpan",
    "common.loading": "Memproses...",
    "common.detail": "Detail",
    "common.public": "Publik",
    "common.traceability": "Traceability",
    "common.settings": "Pengaturan",
    "common.batch": "Batch",
    "common.status": "Status",
    "common.operator": "Operator",
    "common.time": "Waktu",
    "common.network": "Network",
    "common.contract": "Contract",
    "common.mode": "Mode",
    "common.gateway": "Gateway",
    "common.project": "Project",
    "common.url": "URL",
    "common.key": "Key aktif",
    "common.pinata": "Pinata",
    "common.blockchain": "Blockchain",
    "common.metamask": "MetaMask",
    "common.sepolia": "Sepolia",
    "common.etherscan": "Etherscan",
    "common.copyUrl": "Salin URL",
    "common.copied": "Tersalin",
    "common.openPublic": "Buka publik",
    "common.openJson": "Buka JSON",
    "common.noData": "Belum ada data.",
    "common.none": "Tidak ada",
    "common.waiting": "Menunggu",
    "common.ready": "Siap diproses",
    "common.stored": "Tersimpan",
    "common.skipped": "Di-skip",
    "common.completed": "Selesai",
    "common.inProgress": "Sedang Berjalan",
    "common.draft": "Draft",

    "sidebar.batchProduction": "Batch Produksi",
    "sidebar.activityLog": "Log Aktivitas",
    "sidebar.apiDocs": "API Docs",
    "sidebar.toggle": "Buka/tutup sidebar",
    "sidebar.close": "Tutup sidebar",
    "sidebar.logout": "Logout",

    "topbar.newBatch": "Batch Baru",

    "dashboard.title": "Dashboard",
    "dashboard.integrationStatus": "Status integrasi backend",
    "dashboard.metamaskReady": "Manual MetaMask siap",
    "dashboard.totalBatch": "Total Batch",
    "dashboard.finalJson": "JSON Final",

    "batchTable.title": "Batch Produksi",
    "batchTable.code": "Kode",
    "batchTable.type": "Jenis",
    "batchTable.activeStage": "Tahap aktif",
    "batchTable.date": "Tanggal",
    "batchTable.action": "Aksi",
    "batchTable.empty": "Belum ada data batch.",

    "batches.title": "Batch Produksi",

    "newBatch.title": "Buat Batch Baru",
    "newBatch.code": "Kode Batch",
    "newBatch.type": "Jenis Teh",
    "newBatch.gardenBlock": "Blok Kebun",
    "newBatch.harvestDate": "Tanggal Panen",
    "newBatch.notes": "Catatan Awal",
    "newBatch.notesPlaceholder": "Catatan batch awal.",
    "newBatch.save": "Simpan Batch",
    "newBatch.saving": "Menyimpan...",
    "newBatch.error": "Gagal membuat batch baru",

    "stageForm.title": "Input Tahap {{stage}}",
    "stageForm.placeholder": "Masukkan {{field}}",
    "stageForm.save": "Simpan Tahap",
    "stageForm.saving": "Menyimpan ke Supabase...",
    "stageForm.error": "Gagal menyimpan tahapan",

    "batchDetail.title": "Detail Batch {{batchCode}}",
    "batchDetail.code": "Kode Batch",
    "batchDetail.harvestDate": "Tanggal panen",
    "batchDetail.workflowMode": "Mode alur",
    "batchDetail.activeNow": "Tahap aktif sekarang: {{count}}",
    "batchDetail.finalCidSepolia": "Final CID di Sepolia",
    "batchDetail.network": "Network: {{network}}",
    "batchDetail.openFinalTx": "Buka tx final",
    "batchDetail.noActiveStage": "tidak ada",
    "batchDetail.quickActions": "Panel Aksi Cepat",
    "batchDetail.loading": "Memuat data batch...",
    "batchDetail.fullTraceability": "Lihat traceability lengkap",
    "batchDetail.readyStages": "Tahap siap diinput",
    "batchDetail.inputStage": "Input tahap",
    "batchDetail.noActive": "Belum ada tahap aktif saat ini.",
    "batchDetail.skippableStages": "Tahap opsional yang bisa di-skip dari awal",
    "batchDetail.currentStatus": "Status saat ini: {{status}}",
    "batchDetail.skipStage": "Skip tahap",
    "batchDetail.savingSkip": "Menyimpan skip...",
    "batchDetail.allOptionalDecided": "Semua tahap opsional sudah diputuskan.",
    "batchDetail.summary": "Ringkasan Jejak Batch",
    "batchDetail.finalTx": "Tx final",
    "batchDetail.finalJson": "JSON final",
    "batchDetail.activeStage": "Tahap aktif",
    "batchDetail.optionalStage": "Tahap opsional",
    "batchDetail.quickLinks": "Link cepat",
    "batchDetail.defaultSkipReason": "Keputusan skip dari awal proses",
    "batchDetail.workflowGuide": "Panduan Alur Produksi",
    "batchDetail.workflowGuideDescription": "Gunakan referensi ini untuk mencocokkan tahapan aktual batch dengan jenis teh yang diproduksi.",
    "batchDetail.selectedWorkflow": "Alur jenis teh batch ini",
    "batchDetail.allWorkflows": "Referensi semua alur",

    "traceability.title": "Traceability",
    "traceability.batchList": "Daftar Batch",
    "traceability.activeStage": "Tahap aktif: {{stages}}",
    "traceability.pickBatch": "Pilih salah satu batch untuk melihat traceability.",

    "timeline.title": "Timeline Tahapan",
    "timeline.badge": "Dynamic multi-path",
    "timeline.skippable": "Bisa di-skip dari awal",
    "timeline.prerequisite": "Prasyarat: {{stages}}",
    "timeline.skipReason": "Alasan skip:",
    "timeline.supabaseRecord": "Record Supabase",
    "timeline.blockchainAnchor": "Anchor blockchain",
    "timeline.waitingCid": "Menunggu CID final batch",
    "timeline.empty": "Tidak ada tahap yang ditampilkan.",

    "manualAnchor.title": "Finalisasi blockchain manual",
    "manualAnchor.cid": "CID final Pinata",
    "manualAnchor.status": "Status Sepolia",
    "manualAnchor.waitingManual": "Menunggu transaksi manual",
    "manualAnchor.anchored": "CID final sudah tercatat on-chain",
    "manualAnchor.send": "Kirim CID via MetaMask",
    "manualAnchor.waiting": "Menunggu konfirmasi...",
    "manualAnchor.batchIncomplete": "Selesaikan atau skip semua tahap dulu agar JSON final bisa dibuat.",
    "manualAnchor.pinataFailed": "Gagal membuat JSON final di Pinata.",
    "manualAnchor.pinataMock": "PINATA_JWT belum aktif; CID mock tidak dikirim ke blockchain.",
    "manualAnchor.cidMissing": "CID final Pinata belum tersedia.",
    "manualAnchor.contractMissing": "CONTRACT_ADDRESS belum dikonfigurasi.",
    "manualAnchor.walletMissing": "Hubungkan MetaMask dari tombol wallet di kanan atas.",
    "manualAnchor.receiptFailed": "Transaksi gagal dikonfirmasi di Sepolia.",
    "manualAnchor.recordFailed": "Transaksi berhasil, tapi gagal menyimpan tx hash ke Supabase.",
    "manualAnchor.cancelled": "Transaksi dibatalkan atau gagal dari MetaMask.",

    "qr.title": "Barcode traceability publik",

    "reports.title": "Log Aktivitas",
    "reports.stage": "Tahap",
    "reports.anchor": "Anchor Batch",
    "reports.waitingCid": "Menunggu CID final",
    "reports.empty": "Belum ada aktivitas.",

    "settings.title": "Pengaturan",
    "settings.languageTitle": "Bahasa",
    "settings.integrationStatus": "Status integrasi",
    "settings.publishableKey": "Publishable key",
    "settings.walletConnect": "Wallet connect",
    "settings.projectId": "WalletConnect Project ID",
    "settings.desktopWallet": "Desktop wallet",

    "apiDocs.title": "API Docs",
    "apiDocs.badge": "Dokumentasi API",
    "apiDocs.lockedTitle": "API Docs terkunci",
    "apiDocs.lockedDescription": "Masukkan password khusus untuk membuka daftar endpoint. Password ini hanya melindungi halaman dokumentasi, bukan akses API untuk mobile app.",
    "apiDocs.password": "Password API Docs",
    "apiDocs.unlock": "Buka API Docs",
    "apiDocs.unlockFailed": "Gagal membuka API Docs",
    "apiDocs.lockAgain": "Kunci lagi",
    "apiDocs.changePasswordTitle": "Ubah password API Docs",
    "apiDocs.changePasswordDescription": "Password disimpan di Supabase dan bisa diganti kapan saja oleh admin.",
    "apiDocs.currentPassword": "Password lama",
    "apiDocs.newPassword": "Password baru",
    "apiDocs.updatePassword": "Simpan password",
    "apiDocs.changePasswordSuccess": "Password API Docs berhasil diperbarui",
    "apiDocs.changePasswordFailed": "Gagal mengubah password API Docs",
    "apiDocs.basePath": "Base path",
    "apiDocs.auth": "Auth API",
    "apiDocs.headers": "Headers",
    "apiDocs.params": "Params",
    "apiDocs.body": "Body",
    "apiDocs.examples": "Contoh",
    "apiDocs.success": "Success response",
    "apiDocs.errors": "Error response",
    "apiDocs.mobileUse": "Dipakai mobile",
    "apiDocs.mobileFlow": "Alur Implementasi Mobile",
    "apiDocs.enums": "Enum dan Status",
    "apiDocs.productionFlows": "Alur Produksi per Jenis Teh",
    "apiDocs.stageFields": "Field Form per Tahap",
    "apiDocs.responseModels": "Model Response",
    "apiDocs.commonErrors": "Error Umum",

    "login.heading": "Sistem Traceability Produksi Teh",
    "login.title": "Login Admin",
    "login.email": "Email",
    "login.password": "Password",
    "login.submit": "Masuk ke Dashboard",
    "login.demo": "Demo login:",
    "login.error": "Login gagal",

    "publicTrace.badge": "Public Traceability",
    "publicTrace.unavailable": "Traceability tidak tersedia",
    "publicTrace.notFound": "Traceability tidak ditemukan.",
    "publicTrace.loading": "Memuat informasi traceability...",
    "publicTrace.stageNotRecorded": "Tahap belum tercatat.",
    "publicTrace.emptyStages": "Belum ada tahap traceability yang bisa ditampilkan.",
    "publicTrace.gardenMissing": "Blok kebun belum diisi",
    "publicTrace.harvestDate": "Tanggal Panen",
    "publicTrace.stagesShown": "Tahap Tampil",
    "publicTrace.stagesCompleted": "Tahap Selesai",
    "publicTrace.sepoliaTx": "Transaksi Sepolia",
    "publicTrace.blockchainValidation": "Validasi Blockchain",
    "publicTrace.notAnchored": "Belum anchored",
  },
  en: {
    "common.active": "Active",
    "common.inactive": "Inactive",
    "common.configured": "Configured",
    "common.notConfigured": "Not configured",
    "common.back": "Back",
    "common.cancel": "Cancel",
    "common.save": "Save",
    "common.loading": "Processing...",
    "common.detail": "Detail",
    "common.public": "Public",
    "common.traceability": "Traceability",
    "common.settings": "Settings",
    "common.batch": "Batch",
    "common.status": "Status",
    "common.operator": "Operator",
    "common.time": "Time",
    "common.network": "Network",
    "common.contract": "Contract",
    "common.mode": "Mode",
    "common.gateway": "Gateway",
    "common.project": "Project",
    "common.url": "URL",
    "common.key": "Active key",
    "common.pinata": "Pinata",
    "common.blockchain": "Blockchain",
    "common.metamask": "MetaMask",
    "common.sepolia": "Sepolia",
    "common.etherscan": "Etherscan",
    "common.copyUrl": "Copy URL",
    "common.copied": "Copied",
    "common.openPublic": "Open public",
    "common.openJson": "Open JSON",
    "common.noData": "No data.",
    "common.none": "None",
    "common.waiting": "Waiting",
    "common.ready": "Ready",
    "common.stored": "Stored",
    "common.skipped": "Skipped",
    "common.completed": "Completed",
    "common.inProgress": "In Progress",
    "common.draft": "Draft",

    "sidebar.batchProduction": "Production Batches",
    "sidebar.activityLog": "Activity Log",
    "sidebar.apiDocs": "API Docs",
    "sidebar.toggle": "Toggle sidebar",
    "sidebar.close": "Close sidebar",
    "sidebar.logout": "Logout",

    "topbar.newBatch": "New Batch",

    "dashboard.title": "Dashboard",
    "dashboard.integrationStatus": "Backend integration status",
    "dashboard.metamaskReady": "Manual MetaMask ready",
    "dashboard.totalBatch": "Total Batches",
    "dashboard.finalJson": "Final JSON",

    "batchTable.title": "Production Batches",
    "batchTable.code": "Code",
    "batchTable.type": "Type",
    "batchTable.activeStage": "Active stage",
    "batchTable.date": "Date",
    "batchTable.action": "Action",
    "batchTable.empty": "No batch data yet.",

    "batches.title": "Production Batches",

    "newBatch.title": "Create New Batch",
    "newBatch.code": "Batch Code",
    "newBatch.type": "Tea Type",
    "newBatch.gardenBlock": "Garden Block",
    "newBatch.harvestDate": "Harvest Date",
    "newBatch.notes": "Initial Notes",
    "newBatch.notesPlaceholder": "Initial batch notes.",
    "newBatch.save": "Save Batch",
    "newBatch.saving": "Saving...",
    "newBatch.error": "Failed to create batch",

    "stageForm.title": "Input Stage {{stage}}",
    "stageForm.placeholder": "Enter {{field}}",
    "stageForm.save": "Save Stage",
    "stageForm.saving": "Saving to Supabase...",
    "stageForm.error": "Failed to save stage",

    "batchDetail.title": "Batch Detail {{batchCode}}",
    "batchDetail.code": "Batch Code",
    "batchDetail.harvestDate": "Harvest date",
    "batchDetail.workflowMode": "Workflow mode",
    "batchDetail.activeNow": "Active stages now: {{count}}",
    "batchDetail.finalCidSepolia": "Final CID on Sepolia",
    "batchDetail.network": "Network: {{network}}",
    "batchDetail.openFinalTx": "Open final tx",
    "batchDetail.noActiveStage": "none",
    "batchDetail.quickActions": "Quick Actions",
    "batchDetail.loading": "Loading batch data...",
    "batchDetail.fullTraceability": "View full traceability",
    "batchDetail.readyStages": "Stages ready for input",
    "batchDetail.inputStage": "Input stage",
    "batchDetail.noActive": "No active stage right now.",
    "batchDetail.skippableStages": "Optional stages available for early skip",
    "batchDetail.currentStatus": "Current status: {{status}}",
    "batchDetail.skipStage": "Skip stage",
    "batchDetail.savingSkip": "Saving skip...",
    "batchDetail.allOptionalDecided": "All optional stages have been decided.",
    "batchDetail.summary": "Batch Trace Summary",
    "batchDetail.finalTx": "Final tx",
    "batchDetail.finalJson": "Final JSON",
    "batchDetail.activeStage": "Active stage",
    "batchDetail.optionalStage": "Optional stage",
    "batchDetail.quickLinks": "Quick links",
    "batchDetail.defaultSkipReason": "Early process skip decision",
    "batchDetail.workflowGuide": "Production Flow Guide",
    "batchDetail.workflowGuideDescription": "Use this reference to compare the actual batch stages with the tea type being produced.",
    "batchDetail.selectedWorkflow": "This batch tea flow",
    "batchDetail.allWorkflows": "All flow references",

    "traceability.title": "Traceability",
    "traceability.batchList": "Batch List",
    "traceability.activeStage": "Active stage: {{stages}}",
    "traceability.pickBatch": "Select a batch to view traceability.",

    "timeline.title": "Stage Timeline",
    "timeline.badge": "Dynamic multi-path",
    "timeline.skippable": "Can be skipped early",
    "timeline.prerequisite": "Prerequisites: {{stages}}",
    "timeline.skipReason": "Skip reason:",
    "timeline.supabaseRecord": "Supabase record",
    "timeline.blockchainAnchor": "Blockchain anchor",
    "timeline.waitingCid": "Waiting for final batch CID",
    "timeline.empty": "No stages to show.",

    "manualAnchor.title": "Manual blockchain finalization",
    "manualAnchor.cid": "Final Pinata CID",
    "manualAnchor.status": "Sepolia Status",
    "manualAnchor.waitingManual": "Waiting for manual transaction",
    "manualAnchor.anchored": "Final CID is recorded on-chain",
    "manualAnchor.send": "Send CID via MetaMask",
    "manualAnchor.waiting": "Waiting for confirmation...",
    "manualAnchor.batchIncomplete": "Complete or skip every stage before creating the final JSON.",
    "manualAnchor.pinataFailed": "Failed to create final JSON in Pinata.",
    "manualAnchor.pinataMock": "PINATA_JWT is not active; mock CID is not sent to blockchain.",
    "manualAnchor.cidMissing": "Final Pinata CID is not available.",
    "manualAnchor.contractMissing": "CONTRACT_ADDRESS is not configured.",
    "manualAnchor.walletMissing": "Connect MetaMask from the wallet button in the topbar.",
    "manualAnchor.receiptFailed": "Transaction failed to confirm on Sepolia.",
    "manualAnchor.recordFailed": "Transaction succeeded, but failed to save tx hash to Supabase.",
    "manualAnchor.cancelled": "Transaction was cancelled or failed from MetaMask.",

    "qr.title": "Public traceability barcode",

    "reports.title": "Activity Log",
    "reports.stage": "Stage",
    "reports.anchor": "Batch Anchor",
    "reports.waitingCid": "Waiting for final CID",
    "reports.empty": "No activity yet.",

    "settings.title": "Settings",
    "settings.languageTitle": "Language",
    "settings.integrationStatus": "Integration status",
    "settings.publishableKey": "Publishable key",
    "settings.walletConnect": "Wallet connect",
    "settings.projectId": "WalletConnect Project ID",
    "settings.desktopWallet": "Desktop wallet",

    "apiDocs.title": "API Docs",
    "apiDocs.badge": "API Documentation",
    "apiDocs.lockedTitle": "API Docs locked",
    "apiDocs.lockedDescription": "Enter the dedicated password to open the endpoint list. This password only protects the documentation page, not mobile app API access.",
    "apiDocs.password": "API Docs Password",
    "apiDocs.unlock": "Open API Docs",
    "apiDocs.unlockFailed": "Failed to open API Docs",
    "apiDocs.lockAgain": "Lock again",
    "apiDocs.changePasswordTitle": "Change API Docs password",
    "apiDocs.changePasswordDescription": "The password is stored in Supabase and can be changed anytime by an admin.",
    "apiDocs.currentPassword": "Current password",
    "apiDocs.newPassword": "New password",
    "apiDocs.updatePassword": "Save password",
    "apiDocs.changePasswordSuccess": "API Docs password updated",
    "apiDocs.changePasswordFailed": "Failed to change API Docs password",
    "apiDocs.basePath": "Base path",
    "apiDocs.auth": "API auth",
    "apiDocs.headers": "Headers",
    "apiDocs.params": "Params",
    "apiDocs.body": "Body",
    "apiDocs.examples": "Examples",
    "apiDocs.success": "Success response",
    "apiDocs.errors": "Error response",
    "apiDocs.mobileUse": "Used by mobile",
    "apiDocs.mobileFlow": "Mobile Implementation Flow",
    "apiDocs.enums": "Enums and Statuses",
    "apiDocs.productionFlows": "Production Flow by Tea Type",
    "apiDocs.stageFields": "Stage Form Fields",
    "apiDocs.responseModels": "Response Models",
    "apiDocs.commonErrors": "Common Errors",

    "login.heading": "Tea Production Traceability System",
    "login.title": "Admin Login",
    "login.email": "Email",
    "login.password": "Password",
    "login.submit": "Enter Dashboard",
    "login.demo": "Demo login:",
    "login.error": "Login failed",

    "publicTrace.badge": "Public Traceability",
    "publicTrace.unavailable": "Traceability unavailable",
    "publicTrace.notFound": "Traceability not found.",
    "publicTrace.loading": "Loading traceability information...",
    "publicTrace.stageNotRecorded": "Stage has not been recorded.",
    "publicTrace.emptyStages": "No traceability stage can be displayed yet.",
    "publicTrace.gardenMissing": "Garden block not provided",
    "publicTrace.harvestDate": "Harvest Date",
    "publicTrace.stagesShown": "Stages Shown",
    "publicTrace.stagesCompleted": "Stages Completed",
    "publicTrace.sepoliaTx": "Sepolia Transaction",
    "publicTrace.blockchainValidation": "Blockchain Validation",
    "publicTrace.notAnchored": "Not anchored",
  },
};

const languageLabels = {
  id: "Indonesia",
  en: "English",
};

function interpolate(template, values) {
  return template.replace(/\{\{(\w+)\}\}/g, (_, key) => values?.[key] ?? "");
}

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(() => {
    const stored = localStorage.getItem(STORAGE_KEY);
    return stored === "en" || stored === "id" ? stored : "id";
  });

  useEffect(() => {
    localStorage.setItem(STORAGE_KEY, language);
    document.documentElement.lang = language === "en" ? "en" : "id";
  }, [language]);

  const value = useMemo(() => {
    const t = (key, values) => {
      const template = dictionaries[language]?.[key] || dictionaries.id[key] || key;
      return interpolate(template, values);
    };

    return {
      language,
      setLanguage: setLanguageState,
      languageLabels,
      t,
    };
  }, [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  return useContext(LanguageContext);
}
