import { createContext, useContext, useEffect, useMemo, useState } from "react";

const STORAGE_KEY = "tealabs-language";

const dictionaries = {
  id: {
    "common.active": "Aktif",
    "common.inactive": "Belum aktif",
    "common.configured": "Sudah diisi",
    "common.notConfigured": "Belum diisi",
    "common.back": "Kembali",
    "common.cancel": "Batal",
    "common.save": "Simpan",
    "common.loading": "Memproses...",
    "common.detail": "Detail",
    "common.public": "Publik",
    "common.traceability": "Ketertelusuran",
    "common.settings": "Pengaturan",
    "common.batch": "Batch",
    "common.status": "Status",
    "common.operator": "Operator",
    "common.time": "Waktu",
    "common.network": "Jaringan",
    "common.contract": "Kontrak",
    "common.mode": "Mode",
    "common.gateway": "Gateway",
    "common.project": "Proyek",
    "common.url": "URL",
    "common.key": "Kunci aktif",
    "common.pinata": "Pinata",
    "common.blockchain": "Blockchain",
    "common.metamask": "MetaMask",
    "common.sepolia": "Sepolia",
    "common.etherscan": "Etherscan",
    "common.chainId": "Chain ID",
    "common.event": "Peristiwa",
    "common.finalCid": "Final CID",
    "common.jsonPinata": "JSON Pinata",
    "common.txHash": "Hash tx",
    "common.copyUrl": "Salin URL",
    "common.copied": "Tersalin",
    "common.openPublic": "Buka publik",
    "common.openJson": "Buka JSON",
    "common.noData": "Belum ada data.",
    "common.none": "Tidak ada",
    "common.waiting": "Menunggu",
    "common.ready": "Siap diproses",
    "common.stored": "Tersimpan",
    "common.skipped": "Dilewati",
    "common.completed": "Selesai",
    "common.inProgress": "Sedang berjalan",
    "common.draft": "Draft",

    "sidebar.batchProduction": "Batch produksi",
    "sidebar.activityLog": "Log aktivitas",
    "sidebar.apiDocs": "Dokumentasi API",
    "sidebar.toggle": "Buka/tutup sidebar",
    "sidebar.close": "Tutup sidebar",
    "sidebar.logout": "Logout",

    "topbar.newBatch": "Batch baru",
    "topbar.notifications": "Notifikasi",
    "topbar.myProfile": "Profil saya",

    "wallet.connecting": "Menghubungkan",
    "wallet.connect": "Hubungkan",
    "wallet.wrongNetwork": "Network salah",
    "wallet.wallet": "Wallet",

    "profile.title": "Profil saya",
    "profile.name": "Nama",
    "profile.email": "Email",
    "profile.role": "Peran",
    "profile.resetPassword": "Reset kata sandi",
    "profile.currentPassword": "Kata sandi lama",
    "profile.newPassword": "Kata sandi baru",
    "profile.confirmPassword": "Konfirmasi kata sandi baru",
    "profile.resetting": "Menyimpan...",
    "profile.passwordRequired": "Semua kolom kata sandi wajib diisi.",
    "profile.passwordMin": "Kata sandi baru minimal 6 karakter.",
    "profile.passwordMismatch": "Konfirmasi kata sandi baru tidak sama.",
    "profile.passwordSuccess": "Kata sandi berhasil diperbarui.",
    "profile.passwordFailed": "Gagal memperbarui kata sandi.",
    "profile.confirmTitle": "Reset kata sandi sekarang?",
    "profile.confirmDescription": "Setelah kata sandi direset, login berikutnya harus memakai kata sandi baru. Pastikan kata sandi baru sudah benar sebelum melanjutkan.",
    "profile.confirmAction": "Ya, reset kata sandi",

    "notifications.title": "Notifikasi",
    "notifications.unreadCount": "{{count}} belum dibaca",
    "notifications.markAllRead": "Tandai semua dibaca",
    "notifications.clearAll": "Hapus semua notifikasi",
    "notifications.emptyTitle": "Belum ada notifikasi",
    "notifications.emptyDescription": "Aktivitas batch, input tahap, tahap dilewati, dan blockchain akan muncul di sini.",
    "notifications.batchCreatedTitle": "Batch baru dibuat",
    "notifications.batchCreatedMessage": "{{batchCode}} sudah masuk ke daftar produksi.",
    "notifications.stageSavedTitle": "Tahap tersimpan",
    "notifications.stageSavedMessage": "{{stage}} untuk {{batchCode}} berhasil dicatat.",
    "notifications.stageSkippedTitle": "Tahap dilewati",
    "notifications.stageSkippedMessage": "{{stage}} untuk {{batchCode}} dicatat sebagai tahap yang dilewati.",
    "notifications.blockchainAnchoredTitle": "Blockchain selesai",
    "notifications.blockchainAnchoredMessage": "{{batchCode}} sudah selesai dan tx final tersimpan.",

    "dashboard.title": "Dashboard",
    "dashboard.integrationStatus": "Status integrasi backend",
    "dashboard.metamaskReady": "Manual MetaMask siap",
    "dashboard.totalBatch": "Total batch",
    "dashboard.finalJson": "JSON final",
    "dashboard.transactionCosts": "Biaya gas batch selesai",
    "dashboard.totalGasFee": "Total biaya gas",
    "dashboard.averageGasFee": "Rata-rata per batch",
    "dashboard.recordedGasFees": "Biaya tersedia",
    "dashboard.gasUsed": "Gas terpakai",
    "dashboard.gasPrice": "Harga gas",
    "dashboard.viewTx": "Buka transaksi",
    "dashboard.refreshEtherscan": "Perbarui Etherscan",
    "dashboard.gasFeeUnavailable": "Biaya gas belum tersedia dari Etherscan.",
    "dashboard.gasFeeLoadFailed": "Gagal mengambil biaya gas dari Etherscan.",
    "dashboard.marketRateLoadFailed": "Gagal mengambil kurs ETH USD/IDR.",
    "dashboard.etherscanMissing": "ETHERSCAN_API_KEY belum dikonfigurasi di backend.",
    "dashboard.noTransactionCosts": "Belum ada batch selesai yang sudah dikirim ke blockchain.",

    "batchTable.title": "Batch produksi",
    "batchTable.code": "Kode",
    "batchTable.type": "Jenis",
    "batchTable.activeStage": "Tahap aktif",
    "batchTable.date": "Tanggal",
    "batchTable.action": "Aksi",
    "batchTable.empty": "Belum ada data batch.",

    "batches.title": "Batch produksi",

    "newBatch.title": "Buat batch baru",
    "newBatch.code": "Kode batch",
    "newBatch.type": "Jenis teh",
    "newBatch.gardenBlock": "Blok kebun",
    "newBatch.harvestDate": "Tanggal panen",
    "newBatch.notes": "Catatan awal",
    "newBatch.notesPlaceholder": "Catatan batch awal.",
    "newBatch.save": "Simpan batch",
    "newBatch.saving": "Menyimpan...",
    "newBatch.error": "Gagal membuat batch baru",

    "stageForm.title": "Input tahap {{stage}}",
    "stageForm.placeholder": "Masukkan {{field}}",
    "stageForm.save": "Simpan tahap",
    "stageForm.saving": "Menyimpan ke Supabase...",
    "stageForm.error": "Gagal menyimpan tahapan",

    "batchDetail.title": "Detail batch {{batchCode}}",
    "batchDetail.code": "Kode batch",
    "batchDetail.harvestDate": "Tanggal panen",
    "batchDetail.workflowMode": "Mode alur",
    "batchDetail.activeNow": "Tahap aktif sekarang: {{count}}",
    "batchDetail.finalCidSepolia": "Final CID di Sepolia",
    "batchDetail.network": "Jaringan: {{network}}",
    "batchDetail.openFinalTx": "Buka transaksi final",
    "batchDetail.noActiveStage": "tidak ada",
    "batchDetail.quickActions": "Panel aksi cepat",
    "batchDetail.loading": "Memuat data batch...",
    "batchDetail.fullTraceability": "Lihat ketertelusuran lengkap",
    "batchDetail.readyStages": "Tahap siap diinput",
    "batchDetail.inputStage": "Input tahap",
    "batchDetail.noActive": "Belum ada tahap aktif saat ini.",
    "batchDetail.skippableStages": "Tahap opsional yang bisa dilewati dari awal",
    "batchDetail.currentStatus": "Status saat ini: {{status}}",
    "batchDetail.skipStage": "Lewati tahap",
    "batchDetail.savingSkip": "Menyimpan keputusan...",
    "batchDetail.confirmSkip": "Konfirmasi lewati",
    "batchDetail.skipWarningTitle": "Lewati {{stage}}?",
    "batchDetail.skipWarningDescription": "Tahap ini akan dilewati dan dicatat di timeline batch. Pastikan keputusan ini benar sebelum melanjutkan.",
    "batchDetail.skipReasonLabel": "Alasan melewati tahap",
    "batchDetail.skipReasonPlaceholder": "Tuliskan alasan kenapa tahap ini dilewati.",
    "batchDetail.skipReasonRequired": "Alasan melewati tahap wajib diisi.",
    "batchDetail.allOptionalDecided": "Semua tahap opsional sudah diputuskan.",
    "batchDetail.summary": "Ringkasan jejak batch",
    "batchDetail.finalTx": "Tx final",
    "batchDetail.finalJson": "JSON final",
    "batchDetail.activeStage": "Tahap aktif",
    "batchDetail.optionalStage": "Tahap opsional",
    "batchDetail.quickLinks": "Link cepat",
    "batchDetail.defaultSkipReason": "Keputusan melewati tahap dari awal proses",
    "batchDetail.workflowGuide": "Panduan alur produksi",
    "batchDetail.workflowGuideDescription": "Gunakan referensi ini untuk mencocokkan tahapan aktual batch dengan jenis teh yang diproduksi.",
    "batchDetail.selectedWorkflow": "Alur jenis teh batch ini",
    "batchDetail.allWorkflows": "Referensi semua alur",

    "traceability.title": "Ketertelusuran",
    "traceability.batchList": "Daftar batch",
    "traceability.completedOnly": "Hanya batch yang sudah selesai.",
    "traceability.noCompletedBatch": "Belum ada batch selesai yang bisa ditampilkan.",
    "traceability.activeStage": "Tahap aktif: {{stages}}",
    "traceability.pickBatch": "Pilih salah satu batch untuk melihat ketertelusuran.",

    "timeline.title": "Timeline tahapan",
    "timeline.badge": "Dynamic multi-path",
    "timeline.skippable": "Bisa dilewati dari awal",
    "timeline.prerequisite": "Prasyarat: {{stages}}",
    "timeline.skipReason": "Alasan dilewati:",
    "timeline.supabaseRecord": "Data Supabase",
    "timeline.blockchainAnchor": "Catatan blockchain",
    "timeline.waitingCid": "Menunggu CID final batch",
    "timeline.empty": "Tidak ada tahap yang ditampilkan.",

    "manualAnchor.title": "Finalisasi blockchain manual",
    "manualAnchor.cid": "CID final Pinata",
    "manualAnchor.status": "Status Sepolia",
    "manualAnchor.waitingManual": "Menunggu transaksi manual",
    "manualAnchor.anchored": "CID final sudah tercatat on-chain",
    "manualAnchor.send": "Kirim CID via MetaMask",
    "manualAnchor.waiting": "Menunggu konfirmasi...",
    "manualAnchor.batchIncomplete": "Selesaikan atau lewati semua tahap dulu agar JSON final bisa dibuat.",
    "manualAnchor.pinataFailed": "Gagal membuat JSON final di Pinata.",
    "manualAnchor.pinataMock": "PINATA_JWT belum aktif; CID mock tidak dikirim ke blockchain.",
    "manualAnchor.cidMissing": "CID final Pinata belum tersedia.",
    "manualAnchor.contractMissing": "Alamat smart contract belum dikonfigurasi.",
    "manualAnchor.walletMissing": "Hubungkan MetaMask dari tombol wallet di kanan atas.",
    "manualAnchor.receiptFailed": "Transaksi gagal dikonfirmasi di Sepolia.",
    "manualAnchor.recordFailed": "Transaksi berhasil, tapi gagal menyimpan tx hash ke Supabase.",
    "manualAnchor.cancelled": "Transaksi dibatalkan atau gagal dari MetaMask.",

    "qr.title": "Barcode ketertelusuran publik",

    "reports.title": "Log aktivitas",
    "reports.stage": "Tahap",
    "reports.anchor": "Catatan batch",
    "reports.waitingCid": "Menunggu CID final",
    "reports.empty": "Belum ada aktivitas.",

    "settings.title": "Pengaturan",
    "settings.languageTitle": "Bahasa",
    "settings.integrationStatus": "Status integrasi",
    "settings.publishableKey": "Publishable key",
    "settings.walletConnect": "WalletConnect",
    "settings.projectId": "WalletConnect Project ID",
    "settings.desktopWallet": "Wallet desktop",
    "settings.manualMetamask": "Manual MetaMask",

    "blockchainStatus.anchored": "Tercatat on-chain",
    "blockchainStatus.awaitingWallet": "Menunggu tanda tangan wallet",
    "blockchainStatus.pending": "Menunggu",
    "blockchainStatus.failed": "Gagal",

    "apiDocs.title": "Dokumentasi API",
    "apiDocs.badge": "Dokumentasi API",
    "apiDocs.lockedTitle": "Dokumentasi API terkunci",
    "apiDocs.lockedDescription": "Masukkan kata sandi khusus untuk membuka daftar endpoint. Kata sandi ini hanya melindungi halaman dokumentasi, bukan akses API untuk aplikasi mobile.",
    "apiDocs.password": "Kata sandi dokumentasi API",
    "apiDocs.unlock": "Buka dokumentasi API",
    "apiDocs.unlockFailed": "Gagal membuka dokumentasi API",
    "apiDocs.lockAgain": "Kunci lagi",
    "apiDocs.changePasswordTitle": "Ubah kata sandi dokumentasi API",
    "apiDocs.changePasswordDescription": "Kata sandi disimpan di Supabase dan bisa diganti kapan saja oleh admin.",
    "apiDocs.currentPassword": "Kata sandi lama",
    "apiDocs.newPassword": "Kata sandi baru",
    "apiDocs.updatePassword": "Simpan kata sandi",
    "apiDocs.changePasswordSuccess": "Kata sandi dokumentasi API berhasil diperbarui",
    "apiDocs.changePasswordFailed": "Gagal mengubah kata sandi dokumentasi API",
    "apiDocs.basePath": "Base path",
    "apiDocs.baseUrls": "Base URL",
    "apiDocs.auth": "Autentikasi API",
    "apiDocs.headers": "Headers",
    "apiDocs.params": "Params",
    "apiDocs.body": "Body",
    "apiDocs.examples": "Contoh",
    "apiDocs.success": "Respons sukses",
    "apiDocs.errors": "Respons error",
    "apiDocs.mobileUse": "Dipakai mobile",
    "apiDocs.environmentVariables": "Variabel environment",
    "apiDocs.productionChecklist": "Checklist produksi",
    "apiDocs.mobileFlow": "Alur implementasi mobile",
    "apiDocs.enums": "Enum dan Status",
    "apiDocs.productionFlows": "Alur produksi per jenis teh",
    "apiDocs.stageFields": "Field form per tahap",
    "apiDocs.responseModels": "Model respons",
    "apiDocs.commonErrors": "Error umum",

    "login.heading": "Tealabs",
    "login.title": "Masuk admin",
    "login.badge": "Akses aman",
    "login.subtitle": "Masuk ke dashboard operasional Tealabs untuk mengelola batch, ketertelusuran, dan finalisasi produksi.",
    "login.email": "Email",
    "login.emailPlaceholder": "admin@teh.local",
    "login.password": "Kata sandi",
    "login.passwordPlaceholder": "Masukkan kata sandi",
    "login.showPassword": "Tampilkan kata sandi",
    "login.hidePassword": "Sembunyikan kata sandi",
    "login.submit": "Masuk ke dashboard",
    "login.demo": "Demo login:",
    "login.error": "Login gagal",

    "publicTrace.badge": "Ketertelusuran publik",
    "publicTrace.unavailable": "Ketertelusuran tidak tersedia",
    "publicTrace.notFound": "Ketertelusuran tidak ditemukan.",
    "publicTrace.loading": "Memuat informasi traceability...",
    "publicTrace.stageNotRecorded": "Tahap belum tercatat.",
    "publicTrace.emptyStages": "Belum ada tahap ketertelusuran yang bisa ditampilkan.",
    "publicTrace.gardenMissing": "Blok kebun belum diisi",
    "publicTrace.harvestDate": "Tanggal panen",
    "publicTrace.stagesShown": "Tahap tampil",
    "publicTrace.stagesCompleted": "Tahap selesai",
    "publicTrace.sepoliaTx": "Transaksi Sepolia",
    "publicTrace.blockchainValidation": "Validasi blockchain",
    "publicTrace.notAnchored": "Belum tercatat on-chain",
  },
  en: {
    "common.active": "Active",
    "common.inactive": "Inactive",
    "common.configured": "Configured",
    "common.notConfigured": "Not configured",
    "common.back": "Back",
    "common.cancel": "Cancel",
    "common.save": "Save",
    "common.loading": "Processing...",
    "common.detail": "Detail",
    "common.public": "Public",
    "common.traceability": "Traceability",
    "common.settings": "Settings",
    "common.batch": "Batch",
    "common.status": "Status",
    "common.operator": "Operator",
    "common.time": "Time",
    "common.network": "Network",
    "common.contract": "Contract",
    "common.mode": "Mode",
    "common.gateway": "Gateway",
    "common.project": "Project",
    "common.url": "URL",
    "common.key": "Active key",
    "common.pinata": "Pinata",
    "common.blockchain": "Blockchain",
    "common.metamask": "MetaMask",
    "common.sepolia": "Sepolia",
    "common.etherscan": "Etherscan",
    "common.chainId": "Chain ID",
    "common.event": "Event",
    "common.finalCid": "Final CID",
    "common.jsonPinata": "Pinata JSON",
    "common.txHash": "Tx Hash",
    "common.copyUrl": "Copy URL",
    "common.copied": "Copied",
    "common.openPublic": "Open public",
    "common.openJson": "Open JSON",
    "common.noData": "No data.",
    "common.none": "None",
    "common.waiting": "Waiting",
    "common.ready": "Ready",
    "common.stored": "Stored",
    "common.skipped": "Skipped",
    "common.completed": "Completed",
    "common.inProgress": "In progress",
    "common.draft": "Draft",

    "sidebar.batchProduction": "Production batches",
    "sidebar.activityLog": "Activity log",
    "sidebar.apiDocs": "API Docs",
    "sidebar.toggle": "Toggle sidebar",
    "sidebar.close": "Close sidebar",
    "sidebar.logout": "Logout",

    "topbar.newBatch": "New Batch",
    "topbar.notifications": "Notifications",
    "topbar.myProfile": "My profile",

    "wallet.connecting": "Connecting",
    "wallet.connect": "Connect",
    "wallet.wrongNetwork": "Wrong network",
    "wallet.wallet": "Wallet",

    "profile.title": "My profile",
    "profile.name": "Name",
    "profile.email": "Email",
    "profile.role": "Role",
    "profile.resetPassword": "Reset password",
    "profile.currentPassword": "Current password",
    "profile.newPassword": "New password",
    "profile.confirmPassword": "Confirm new password",
    "profile.resetting": "Saving...",
    "profile.passwordRequired": "All password fields are required.",
    "profile.passwordMin": "New password must be at least 6 characters.",
    "profile.passwordMismatch": "New password confirmation does not match.",
    "profile.passwordSuccess": "Password updated successfully.",
    "profile.passwordFailed": "Failed to update password.",
    "profile.confirmTitle": "Reset password now?",
    "profile.confirmDescription": "After the password is reset, the next login must use the new password. Make sure the new password is correct before continuing.",
    "profile.confirmAction": "Yes, reset password",

    "notifications.title": "Notifications",
    "notifications.unreadCount": "{{count}} unread",
    "notifications.markAllRead": "Mark all as read",
    "notifications.clearAll": "Clear all notifications",
    "notifications.emptyTitle": "No notifications yet",
    "notifications.emptyDescription": "Batch activity, stage input, skips, and blockchain updates will appear here.",
    "notifications.batchCreatedTitle": "New batch created",
    "notifications.batchCreatedMessage": "{{batchCode}} has been added to production.",
    "notifications.stageSavedTitle": "Stage saved",
    "notifications.stageSavedMessage": "{{stage}} for {{batchCode}} was recorded.",
    "notifications.stageSkippedTitle": "Stage skipped",
    "notifications.stageSkippedMessage": "{{stage}} for {{batchCode}} was recorded as skipped.",
    "notifications.blockchainAnchoredTitle": "Blockchain completed",
    "notifications.blockchainAnchoredMessage": "{{batchCode}} is complete and the final tx is stored.",

    "dashboard.title": "Dashboard",
    "dashboard.integrationStatus": "Backend integration status",
    "dashboard.metamaskReady": "Manual MetaMask ready",
    "dashboard.totalBatch": "Total batches",
    "dashboard.finalJson": "Final JSON",
    "dashboard.transactionCosts": "Completed batch gas fees",
    "dashboard.totalGasFee": "Total gas fee",
    "dashboard.averageGasFee": "Average per batch",
    "dashboard.recordedGasFees": "Fees available",
    "dashboard.gasUsed": "Gas used",
    "dashboard.gasPrice": "Gas price",
    "dashboard.viewTx": "Open tx",
    "dashboard.refreshEtherscan": "Refresh Etherscan",
    "dashboard.gasFeeUnavailable": "Gas fee is not available from Etherscan yet.",
    "dashboard.gasFeeLoadFailed": "Failed to load gas fees from Etherscan.",
    "dashboard.marketRateLoadFailed": "Failed to load ETH USD/IDR rates.",
    "dashboard.etherscanMissing": "ETHERSCAN_API_KEY is not configured on the backend.",
    "dashboard.noTransactionCosts": "No completed batch has been pushed to blockchain yet.",

    "batchTable.title": "Production batches",
    "batchTable.code": "Code",
    "batchTable.type": "Type",
    "batchTable.activeStage": "Active stage",
    "batchTable.date": "Date",
    "batchTable.action": "Action",
    "batchTable.empty": "No batch data yet.",

    "batches.title": "Production batches",

    "newBatch.title": "Create new batch",
    "newBatch.code": "Batch code",
    "newBatch.type": "Tea type",
    "newBatch.gardenBlock": "Garden block",
    "newBatch.harvestDate": "Harvest date",
    "newBatch.notes": "Initial notes",
    "newBatch.notesPlaceholder": "Initial batch notes.",
    "newBatch.save": "Save batch",
    "newBatch.saving": "Saving...",
    "newBatch.error": "Failed to create batch",

    "stageForm.title": "Input stage {{stage}}",
    "stageForm.placeholder": "Enter {{field}}",
    "stageForm.save": "Save stage",
    "stageForm.saving": "Saving to Supabase...",
    "stageForm.error": "Failed to save stage",

    "batchDetail.title": "Batch detail {{batchCode}}",
    "batchDetail.code": "Batch code",
    "batchDetail.harvestDate": "Harvest date",
    "batchDetail.workflowMode": "Workflow mode",
    "batchDetail.activeNow": "Active stages now: {{count}}",
    "batchDetail.finalCidSepolia": "Final CID on Sepolia",
    "batchDetail.network": "Network: {{network}}",
    "batchDetail.openFinalTx": "Open final tx",
    "batchDetail.noActiveStage": "none",
    "batchDetail.quickActions": "Quick actions",
    "batchDetail.loading": "Loading batch data...",
    "batchDetail.fullTraceability": "View full traceability",
    "batchDetail.readyStages": "Stages ready for input",
    "batchDetail.inputStage": "Input stage",
    "batchDetail.noActive": "No active stage right now.",
    "batchDetail.skippableStages": "Optional stages available for early skip",
    "batchDetail.currentStatus": "Current status: {{status}}",
    "batchDetail.skipStage": "Skip stage",
    "batchDetail.savingSkip": "Saving skip...",
    "batchDetail.confirmSkip": "Confirm skip",
    "batchDetail.skipWarningTitle": "Skip {{stage}}?",
    "batchDetail.skipWarningDescription": "This stage will be skipped and recorded in the batch timeline. Make sure this decision is correct before continuing.",
    "batchDetail.skipReasonLabel": "Skip reason",
    "batchDetail.skipReasonPlaceholder": "Write the reason why this stage is being skipped.",
    "batchDetail.skipReasonRequired": "Skip reason is required.",
    "batchDetail.allOptionalDecided": "All optional stages have been decided.",
    "batchDetail.summary": "Batch trace summary",
    "batchDetail.finalTx": "Final tx",
    "batchDetail.finalJson": "Final JSON",
    "batchDetail.activeStage": "Active stage",
    "batchDetail.optionalStage": "Optional stage",
    "batchDetail.quickLinks": "Quick links",
    "batchDetail.defaultSkipReason": "Early process skip decision",
    "batchDetail.workflowGuide": "Production flow guide",
    "batchDetail.workflowGuideDescription": "Use this reference to compare the actual batch stages with the tea type being produced.",
    "batchDetail.selectedWorkflow": "This batch tea flow",
    "batchDetail.allWorkflows": "All flow references",

    "traceability.title": "Traceability",
    "traceability.batchList": "Batch list",
    "traceability.completedOnly": "Only completed batches are shown.",
    "traceability.noCompletedBatch": "No completed batch is available yet.",
    "traceability.activeStage": "Active stage: {{stages}}",
    "traceability.pickBatch": "Select a batch to view traceability.",

    "timeline.title": "Stage timeline",
    "timeline.badge": "Dynamic multi-path",
    "timeline.skippable": "Can be skipped early",
    "timeline.prerequisite": "Prerequisites: {{stages}}",
    "timeline.skipReason": "Skip reason:",
    "timeline.supabaseRecord": "Supabase record",
    "timeline.blockchainAnchor": "Blockchain anchor",
    "timeline.waitingCid": "Waiting for final batch CID",
    "timeline.empty": "No stages to show.",

    "manualAnchor.title": "Manual blockchain finalization",
    "manualAnchor.cid": "Final Pinata CID",
    "manualAnchor.status": "Sepolia status",
    "manualAnchor.waitingManual": "Waiting for manual transaction",
    "manualAnchor.anchored": "Final CID is recorded on-chain",
    "manualAnchor.send": "Send CID via MetaMask",
    "manualAnchor.waiting": "Waiting for confirmation...",
    "manualAnchor.batchIncomplete": "Complete or skip every stage before creating the final JSON.",
    "manualAnchor.pinataFailed": "Failed to create final JSON in Pinata.",
    "manualAnchor.pinataMock": "PINATA_JWT is not active; mock CID is not sent to blockchain.",
    "manualAnchor.cidMissing": "Final Pinata CID is not available.",
    "manualAnchor.contractMissing": "Smart contract address is not configured.",
    "manualAnchor.walletMissing": "Connect MetaMask from the wallet button in the topbar.",
    "manualAnchor.receiptFailed": "Transaction failed to confirm on Sepolia.",
    "manualAnchor.recordFailed": "Transaction succeeded, but failed to save tx hash to Supabase.",
    "manualAnchor.cancelled": "Transaction was cancelled or failed from MetaMask.",

    "qr.title": "Public traceability barcode",

    "reports.title": "Activity log",
    "reports.stage": "Stage",
    "reports.anchor": "Batch anchor",
    "reports.waitingCid": "Waiting for final CID",
    "reports.empty": "No activity yet.",

    "settings.title": "Settings",
    "settings.languageTitle": "Language",
    "settings.integrationStatus": "Integration status",
    "settings.publishableKey": "Publishable key",
    "settings.walletConnect": "WalletConnect",
    "settings.projectId": "WalletConnect Project ID",
    "settings.desktopWallet": "Desktop wallet",
    "settings.manualMetamask": "Manual MetaMask",

    "blockchainStatus.anchored": "Anchored on-chain",
    "blockchainStatus.awaitingWallet": "Awaiting wallet signature",
    "blockchainStatus.pending": "Pending",
    "blockchainStatus.failed": "Failed",

    "apiDocs.title": "API Docs",
    "apiDocs.badge": "API Documentation",
    "apiDocs.lockedTitle": "API Docs locked",
    "apiDocs.lockedDescription": "Enter the dedicated password to open the endpoint list. This password only protects the documentation page, not mobile app API access.",
    "apiDocs.password": "API Docs password",
    "apiDocs.unlock": "Open API Docs",
    "apiDocs.unlockFailed": "Failed to open API Docs",
    "apiDocs.lockAgain": "Lock again",
    "apiDocs.changePasswordTitle": "Change API Docs password",
    "apiDocs.changePasswordDescription": "The password is stored in Supabase and can be changed anytime by an admin.",
    "apiDocs.currentPassword": "Current password",
    "apiDocs.newPassword": "New password",
    "apiDocs.updatePassword": "Save password",
    "apiDocs.changePasswordSuccess": "API Docs password updated",
    "apiDocs.changePasswordFailed": "Failed to change API Docs password",
    "apiDocs.basePath": "Base path",
    "apiDocs.baseUrls": "Base URLs",
    "apiDocs.auth": "API auth",
    "apiDocs.headers": "Headers",
    "apiDocs.params": "Params",
    "apiDocs.body": "Body",
    "apiDocs.examples": "Examples",
    "apiDocs.success": "Success response",
    "apiDocs.errors": "Error response",
    "apiDocs.mobileUse": "Used by mobile",
    "apiDocs.environmentVariables": "Environment variables",
    "apiDocs.productionChecklist": "Production checklist",
    "apiDocs.mobileFlow": "Mobile implementation flow",
    "apiDocs.enums": "Enums and statuses",
    "apiDocs.productionFlows": "Production flow by tea type",
    "apiDocs.stageFields": "Stage form fields",
    "apiDocs.responseModels": "Response models",
    "apiDocs.commonErrors": "Common errors",

    "login.heading": "Tealabs",
    "login.title": "Admin login",
    "login.badge": "Secure access",
    "login.subtitle": "Sign in to the Tealabs operations dashboard to manage batches, traceability, and production finalization.",
    "login.email": "Email",
    "login.emailPlaceholder": "admin@teh.local",
    "login.password": "Password",
    "login.passwordPlaceholder": "Enter password",
    "login.showPassword": "Show password",
    "login.hidePassword": "Hide password",
    "login.submit": "Enter dashboard",
    "login.demo": "Demo login:",
    "login.error": "Login failed",

    "publicTrace.badge": "Public Traceability",
    "publicTrace.unavailable": "Traceability unavailable",
    "publicTrace.notFound": "Traceability not found.",
    "publicTrace.loading": "Loading traceability information...",
    "publicTrace.stageNotRecorded": "Stage has not been recorded.",
    "publicTrace.emptyStages": "No traceability stage can be displayed yet.",
    "publicTrace.gardenMissing": "Garden block not provided",
    "publicTrace.harvestDate": "Harvest date",
    "publicTrace.stagesShown": "Stages shown",
    "publicTrace.stagesCompleted": "Stages completed",
    "publicTrace.sepoliaTx": "Sepolia Transaction",
    "publicTrace.blockchainValidation": "Blockchain validation",
    "publicTrace.notAnchored": "Not anchored",
  },
};

const languageLabels = {
  id: "ID",
  en: "ENG",
};

function interpolate(template, values) {
  return template.replace(/\{\{(\w+)\}\}/g, (_, key) => values?.[key] ?? "");
}

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(() => {
    const stored = localStorage.getItem(STORAGE_KEY);
    return stored === "en" || stored === "id" ? stored : "id";
  });

  useEffect(() => {
    localStorage.setItem(STORAGE_KEY, language);
    document.documentElement.lang = language === "en" ? "en" : "id";
  }, [language]);

  const value = useMemo(() => {
    const t = (key, values) => {
      const template = dictionaries[language]?.[key] || dictionaries.id[key] || key;
      return interpolate(template, values);
    };

    return {
      language,
      setLanguage: setLanguageState,
      languageLabels,
      t,
    };
  }, [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  return useContext(LanguageContext);
}
